{
 "title": "Emby Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Restart Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{hasPendingRestart}}" }
   ]
  },
  {
   "title": "Update Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{hasUpdateAvailable}}" }
   ]
  },
  {
   "title": "Wan Address",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{wanAdress}}" }
   ]
  },
  {
   "title": "Wan Address",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{localAdress}}" }
   ]
  },
  {
   "title": "Wan Address",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Map Stream",
   "type": "geomap",
   "gridPos": { "h": 23, "w": 10, "x": 0, "y": 4 },
   "targets": [
    { "expr": "emby_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Streams",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 4 },
   "targets": [
    { "expr": "emby_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Streams",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 11 },
   "targets": [
    { "expr": "emby_sessions_count", "legendFormat": "Streams" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 18 },
   "targets": [
    { "expr": "emby_activity" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "emby_media_item" }
   ]
  }
 ]
}