{
 "title": "Emby Dashboard test",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Version No.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Device type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(client) (count_over_time(emby_sessions[4w]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Playback Type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(nowPlayingItemType) (count_over_time(emby_sessions[4w]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_sessions_count", "legendFormat": "Emby Streams" }
   ]
  },
  {
   "title": "Streams",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "emby_sessions_count", "legendFormat": "Emby" },
    {
     "expr": "Plex_sessions_count{state=\"playing\"}",
     "legendFormat": "Plex Music"
    }
   ]
  },
  {
   "title": "Lan Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{localAdress}}" }
   ]
  },
  {
   "title": "Direct Stream",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(emby_sessions{playMethod=\"DirectStream\"})",
     "legendFormat": "DirectStream"
    }
   ]
  },
  {
   "title": "Wan Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{wanAdress}} " }
   ]
  },
  {
   "title": "Playback Method",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(playMethod) (count_over_time(emby_sessions[4w]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "User",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by(username) (count_over_time(emby_sessions[4w]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Direct Play",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(emby_sessions{playMethod=\"Direct Play\"})",
     "legendFormat": "DirectPlay"
    }
   ]
  },
  {
   "title": "Update Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{hasUpdateAvailable}}" }
   ]
  },
  {
   "title": "Restart Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "emby_system_info", "legendFormat": "{{hasPendingRestart}}" }
   ]
  },
  {
   "title": "Transcode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(emby_sessions{playMethod=\"Transcoding\"})",
     "legendFormat": "Transcode"
    }
   ]
  },
  {
   "title": "Current Streams",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "emby_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Streaming info",
   "type": "table",
   "gridPos": { "h": 25, "w": 18, "x": 0, "y": 19 },
   "targets": [
    { "expr": "rate(emby_activity[24h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Map Stream",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "emby_sessions{latitude!=\"0.000000\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Library Info.",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 30 },
   "targets": [
    { "expr": "emby_media_item", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}