name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - v*
      - latest
  pull_request:
    branches:
      - v*
      - latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bagul/goemby_exporter

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download MaxMind DB
        run: |
          LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}
          ACCOUNT_ID=${{ secrets.MAXMIND_ACCOUNT_ID }}
          curl -o maxmind-db.tar.gz -O -J -L -u ${ACCOUNT_ID}:${LICENSE_KEY} "https://download.maxmind.com/geoip/databases/GeoLite2-City/download?suffix=tar.gz"
          tar zxvf maxmind-db.tar.gz
          mv GeoLite2-City_*/GeoLite2-City.mmdb geoip.mmdb
          rm -rf GeoLite2-City_* maxmind-db.tar.gz

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=bagul/goemby_exporter,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          # Le fichier est nommé sans le préfixe "sha256:"
          touch "/tmp/digests/${digest#sha256:}"

      # Calculer un nom d'artifact unique à partir de la variable de matrice
      - name: Set platform artifact name
        id: set_artifact_name
        shell: bash
        run: |
          sanitized=$(echo "${{ matrix.platform }}" | tr '/' '-')
          echo "artifact_name=digests-$sanitized" >> $GITHUB_OUTPUT

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download all digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bagul/goemby_exporter

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version from go file
        id: version
        run: |
          echo ::set-output name=version::$(grep -oP 'version = "\K[^"]+' main.go)

      - name: Create manifest list and push
        working-directory: /tmp/digests
        if: github.event_name != 'pull_request'
        run: |
          DIGEST_ARGS=""
          for digestfile in $(find . -type f); do
            DIGEST_SHA=$(basename "$digestfile")
            DIGEST_ARGS="$DIGEST_ARGS bagul/goemby_exporter@sha256:$DIGEST_SHA"
          done

          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $DIGEST_ARGS

      - name: Inspect image
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect bagul/goemby_exporter:${{ steps.meta.outputs.version }}
